### ISSUE TITLE
Rails version compatibility?

### ISSUE THREAD

**Issue by scribu** [1debit/sql_enum#1]
Hello,

Thanks for this handy gem! Is it supposed to work with Rails 4? I'm getting a loading error when using rake:

```
$ bundle exec rake db:structure:load
rake aborted!
LoadError: cannot load such file -- active_record/connection_adapters/mysql/schema_definitions
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/home/circleci/project/vendor/bundle/gems/sql_enum-0.1.16/lib/active_record/connection_adapters/mysql/column_methods.rb:1:in `<top (required)>'
/home/circleci/project/vendor/bundle/gems/sql_enum-0.1.16/lib/sql_enum.rb:29:in `require_relative'
/home/circleci/project/vendor/bundle/gems/sql_enum-0.1.16/lib/sql_enum.rb:29:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:114:in `require'
/home/circleci/project/config/application.rb:7:in `<top (required)>'
/home/circleci/project/Rakefile:4:in `require'
/home/circleci/project/Rakefile:4:in `<top (required)>'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:82:in `block in run'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/circleci/project/vendor/bundle/bin/rake:23:in `load'
/home/circleci/project/vendor/bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:424:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Exited with code 1
```

**Comment by fzf** [comment]
@scribu sorry for the late response, it looks like the schema_definition file was only added in rails 5. I have bumped the gemspec to ensure rails 5. We previously used [enum_column3](https://rubygems.org/gems/enum_column3) before upgrading, not sure if it works with rails 4.
